### PR TITLE
PA-14053-resque-pool-gem-update

### PR DESCRIPTION
**Pull request by travis-hooper**
### Intro
- We are currently dependent on our forked version of resque-pool, however we would still like to update it to the newest version of resque-pool. This updates our fork to the newest version of resque-pool and then adds our forked changes.
- [x]  Passes all specs in the gem spec directory
- [x] [Passes CI](http://pa-ci.peopleadmin.com/view/Ad-hoc%20jobs/job/Ad-hoc%20Master%20Job/696/)

### CODE REVIEW

**Comment by parkeryoung** [comment]
I wouldn't really advise any changes to this stuff, all of this code is code that we pulled in from the main gem. Changing anything will just result in us being further from the newest version.

LGTM

**Comment by billeisenhauer** [comment]
How do we demarcate our forked changes?  I quickly scanned, but could not tell what are our specific changes.

**Comment by travis-hooper** [comment]
We can demarcate our forked changes [here](https://github.com/PeopleAdmin/resque-pool/compare/f6c7fa16fc450e604ddb9727ac34cd8ab6885d8b...5552b01cd0d613ff05e925af55630fc383637256)

**Comment by joshuaflanagan** [comment]
Another approach would be to rebase the `config_loader` branch onto master, and merge that into a new `deploy` branch. Ideally we should push to get the `config_loader` PR merged into the main gem. It currently has merge conflicts - I can try to work through them, if you give me commit access to this repo.

**Comment by parkeryoung** [comment]
Josh shouldn't we be able to just push this branch to that one? I think `release` and `config_loader` are identical branches.

**Comment by parkeryoung** [comment]
Err deploy

**Comment by joshuaflanagan** [comment]
You do not want to merge this PR into the `config_loader` branch. The
`config_loader` branch just contains the changes that we want applied to
the original gem. It should only contain the 3 commits that provide the new
functionality - it should not contain any "merge" commits - the rest of the
world doesn't care about PA's deploy branch, or any merges into it.

It is generally good practice to rebase a PR branch intended for an open
source repo so that the original repo owners can clearly see the diff,
understand the reason for each commit, and merge it cleanly.

If I were doing it, I would:

(assuming you have a `nevans` remote that references the original repo)

``` sh
git fetch --all
git checkout config_loader
git rebase nevans/master
git push --force #updates remote config_loader branch
git checkout deploy
git reset --harder nevans/master
git merge -m "Merge rebased config_loader" --no-ff config_loader
git push --force #updates remote deploy branch
```

You can always create a tag/branch for the current `deploy` SHA if you want
it for historical reasons.

**Comment by rpond-pa** [comment]
I :heart: how the :ghost: of flanagan shows up to protect us from harm.  Kind of like Patrick Swayze in Ghost but without the weird pottery scene.

**Comment by joshuaflanagan** [comment]
Haha - its too bad I'm not quicker with photoshop

**Comment by parkeryoung** [comment]
Oh weird, when I looked at the config_loader branch on my phone it showed Lance's merge commit. I can resolve the merge conflicts, I already did it once.

**Comment by joshuaflanagan** [comment]
I've pushed up a rebased (and readme) fix to my fork. Please reset
config_loader branch to match my branch (since that is the one used in the
PR to the main repo). You can create a new branch name to refer to the
existing state of config_loader, which is merged into your deploy branch.

From your local repo (assumes 'origin' references the PeopleAdmin fork):

git fetch --all
git remote add josh git@github.com:joshuaflanagan/resque-pool.git   # add a
reference to my fork
git fetch josh
git checkout config_loader
git checkout -b pa_config_loader
git push -u origin pa_config_loader  # push a copy of the current
config_loader state before making any changes
git checkout config_loader                # go back to original
config_loader branch used in the PR
git reset --hard josh/config_loader    # set your config_loader to look
just like mine
git push --force                                  # update the PeopleAdmin
config_loader branch, which updates the PR

This will help us get the main PR approved, which can help get you out of
maintaining a separate fork.
Again, I'd be happy to handle this if you give me temporary commit access
to this public repo (I wouldn't have access to any of your private repos).
May make the PR process go smoother. You always have your local clones of
the repo that you could use to restore its state if you're afraid I'll
screw something up ;)

**Comment by mdellandrea** [comment]
Let soak in the perf test environment a few days. No errors have been encountered. CI is passing.

**Comment by joshuaflanagan** [comment]
FYI - The PA changes have now been accepted into the master branch of resque-pool. You can start referencing nevans/master in your Gemfile, or wait for an official release. Either way, you no longer need to maintain your own fork. :tada:

**Pull request merged**
